# Generated by Django 4.1.1 on 2022-09-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_buy_p_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='p_state',
            field=models.SmallIntegerField(default=0),
        ),
    ]
