# Generated by Django 4.1.1 on 2022-09-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_alter_buy_p_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='p_img',
            field=models.CharField(default='img', max_length=200),
            preserve_default=False,
        ),
    ]
